[package]
name = "grp"
version = "0.1.1"
authors = ["TENX-S <ttenx@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["lib", "staticlib"]


[dependencies]
rand = "0.7.3"