[package]
name = "grp"
version = "0.1.0"
authors = ["TENX-S <ttenx@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
api_g_r_d = { path = "../api_g_r_d" }